/**
 * 影荐墙 Top100 电影数据
 * 综合 IMDb Top 250 / 豆瓣 Top 250 / Letterboxd / 烂番茄 四大榜单加权整合
 * 全部为 2000 年后的电影
 * @type {Array<Object>}
 */
const MOVIES_DATA = [
  // ====================== Top 1-10 ======================
  {
    id: 'm001', rank: 1, title: '千与千寻', originalTitle: 'Spirited Away', year: 2001,
    director: '宫崎骏', cast: ['柊瑠美', '入野自由', '夏木真理', '菅原文太'],
    categories: ['动画', '奇幻', '冒险'], rating: 9.4, region: '日本',
    description: '少女千寻误入神灵世界，为救父母在汤屋中打工成长。宫崎骏以瑰丽想象编织成人童话，关于迷失与找回自我的永恒寓言。',
    quote: '不管前方的路有多苦，只要走的方向正确，都比站在原地更接近幸福。',
    image: 'images/m001.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/5307/sid/1/nid/1.html',
  },
  {
    id: 'm002', rank: 2, title: '蝙蝠侠：黑暗骑士', originalTitle: 'The Dark Knight', year: 2008,
    director: '克里斯托弗·诺兰', cast: ['克里斯蒂安·贝尔', '希斯·莱杰', '艾伦·艾克哈特', '迈克尔·凯恩'],
    categories: ['动作', '犯罪', '剧情'], rating: 9.2, region: '美国',
    description: '蝙蝠侠与小丑的终极对决，混乱与秩序的博弈。希斯·莱杰以癫狂入骨的小丑表演定义超级英雄电影的哲学深度。',
    quote: '黎明前的黑夜总是最深的，但我保证，黎明终会到来。',
    image: 'images/m002.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/210047/sid/1/nid/1.html',
  },
  {
    id: 'm003', rank: 3, title: '指环王3：王者无敌', originalTitle: 'The Lord of the Rings: The Return of the King', year: 2003,
    director: '彼得·杰克逊', cast: ['伊利亚·伍德', '维果·莫滕森', '伊恩·麦克莱恩', '安迪·瑟金斯'],
    categories: ['奇幻', '冒险', '动作'], rating: 9.3, region: '新西兰',
    description: '中土世界的史诗终章，弗罗多踏上末日火山完成护戒使命。11项奥斯卡加冕，影史最伟大的三部曲完美收官。',
    quote: '即使是最小的人，也能改变未来的走向。',
    image: 'images/m003.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/3834/sid/1/nid/1.html',
  },
  {
    id: 'm004', rank: 4, title: '盗梦空间', originalTitle: 'Inception', year: 2010,
    director: '克里斯托弗·诺兰', cast: ['莱昂纳多·迪卡普里奥', '约瑟夫·高登-莱维特', '艾伦·佩吉', '汤姆·哈迪'],
    categories: ['科幻', '动作', '悬疑'], rating: 9.3, region: '美国',
    description: '柯布带领团队进入层层嵌套的梦境植入想法。诺兰以精妙绝伦的叙事迷宫，模糊了梦境与现实的边界。',
    quote: '你在等一列火车，你不知道它将带你去向何方，但那不重要。',
    image: 'images/m004.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241196/sid/1/nid/1.html',
  },
  {
    id: 'm005', rank: 5, title: '寄生虫', originalTitle: 'Parasite', year: 2019,
    director: '奉俊昊', cast: ['宋康昊', '李善均', '赵汝贞', '崔宇植'],
    categories: ['剧情', '悬疑', '惊悚'], rating: 9.0, region: '韩国',
    description: '贫穷的金家四口陆续潜入朴社长家中工作。奉俊昊以类型片手法解剖阶级固化，戛纳金棕榈+奥斯卡最佳影片实至名归。',
    quote: '不是"有钱却很善良"，是"有钱所以善良"。',
    image: 'images/m005.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239723/sid/1/nid/1.html',
  },
  {
    id: 'm006', rank: 6, title: '星际穿越', originalTitle: 'Interstellar', year: 2014,
    director: '克里斯托弗·诺兰', cast: ['马修·麦康纳', '安妮·海瑟薇', '杰西卡·查斯坦', '迈克尔·凯恩'],
    categories: ['科幻', '冒险', '剧情'], rating: 9.4, region: '美国',
    description: '前飞行员库珀穿越虫洞寻找人类新家园，在浩瀚宇宙中，爱穿越维度成为连接过去与未来的桥梁。',
    quote: '爱是唯一可以穿越时间与空间的力量。',
    image: 'images/m006.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/20254/sid/1/nid/1.html',
  },
  {
    id: 'm007', rank: 7, title: '机器人总动员', originalTitle: 'WALL-E', year: 2008,
    director: '安德鲁·斯坦顿', cast: ['本·贝尔特', '艾丽莎·奈特', '杰夫·格尔林', '佛莱德·威拉特'],
    categories: ['动画', '科幻', '冒险'], rating: 9.3, region: '美国',
    description: '孤独的机器人瓦力在废土地球上偶遇探员伊芙，一段跨越星系的纯爱之旅。皮克斯用沉默诠释了最浪漫的宇宙童话。',
    quote: '我不需要你为我做任何事，只要你能和我在一起。',
    image: 'images/m007.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239725/sid/1/nid/1.html',
  },
  {
    id: 'm008', rank: 8, title: '指环王1：魔戒再现', originalTitle: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001,
    director: '彼得·杰克逊', cast: ['伊利亚·伍德', '伊恩·麦克莱恩', '维果·莫滕森', '肖恩·宾'],
    categories: ['奇幻', '冒险', '动作'], rating: 9.1, region: '新西兰',
    description: '霍比特人弗罗多继承魔戒踏上毁灭之旅，九人护戒联盟穿越中土世界。彼得·杰克逊开创了奇幻史诗的新纪元。',
    quote: '当智者选择了回避，历史便由愚者来书写。',
    image: 'images/m008.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/3856/sid/1/nid/1.html',
  },
  {
    id: 'm009', rank: 9, title: '指环王2：双塔奇兵', originalTitle: 'The Lord of the Rings: The Two Towers', year: 2002,
    director: '彼得·杰克逊', cast: ['伊利亚·伍德', '维果·莫滕森', '伊恩·麦克莱恩', '安迪·瑟金斯'],
    categories: ['奇幻', '冒险', '动作'], rating: 9.1, region: '新西兰',
    description: '护戒联盟分崩离析，圣盔谷之战震撼上演。咕噜的登场为史诗注入人性深处的分裂与挣扎。',
    quote: '没有什么是一定的，黎明前的黑暗总是最深。',
    image: 'images/m009.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/3843/sid/1/nid/1.html',
  },
  {
    id: 'm010', rank: 10, title: '寻梦环游记', originalTitle: 'Coco', year: 2017,
    director: '李·昂克里奇', cast: ['安东尼·冈萨雷斯', '盖尔·加西亚·贝纳尔', '本杰明·布拉特', '阿兰娜·乌巴赫'],
    categories: ['动画', '音乐', '家庭'], rating: 9.1, region: '美国',
    description: '热爱音乐的米格尔误入亡灵世界，揭开家族尘封的秘密。当《请记住我》响起，整个影厅都在擦眼泪。',
    quote: '真正的死亡，是世界上再没有一个人记得你。',
    image: 'images/m010.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/13982/sid/1/nid/1.html',
  },

  // ====================== Top 11-20 ======================
  {
    id: 'm011', rank: 11, title: '无间道', originalTitle: 'Infernal Affairs', year: 2002,
    director: '刘伟强 / 麦兆辉', cast: ['刘德华', '梁朝伟', '黄秋生', '曾志伟'],
    categories: ['犯罪', '悬疑', '剧情'], rating: 9.3, region: '中国',
    description: '警匪双方各派卧底渗透对方，两个身份错位的人在无间地狱中挣扎。港片最后的巅峰，马丁·斯科塞斯翻拍亦难超越。',
    quote: '以前我没得选，现在我想做个好人。',
    image: 'images/m011.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/210722/sid/1/nid/1.html',
  },
  {
    id: 'm012', rank: 12, title: '飞屋环游记', originalTitle: 'Up', year: 2009,
    director: '彼特·道格特', cast: ['爱德华·阿斯纳', '克里斯托弗·普卢默', '乔丹·长井', '鲍勃·彼德森'],
    categories: ['动画', '冒险', '剧情'], rating: 9.0, region: '美国',
    description: '78岁老人卡尔用上万气球带着房子飞向南美，意外带上小胖墩罗素。开篇四分钟蒙太奇浓缩一生的爱与遗憾。',
    quote: '幸福不是冒险的终点，而是一路同行的每一天。',
    image: 'images/m012.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/27221/sid/1/nid/1.html',
  },
  {
    id: 'm013', rank: 13, title: '触不可及', originalTitle: 'Intouchables', year: 2011,
    director: '奥利维耶·纳卡什 / 埃里克·托莱达诺', cast: ['弗朗索瓦·克鲁塞', '奥马尔·赛', '奥黛丽·弗洛特', '安娜·勒尼'],
    categories: ['剧情', '喜剧'], rating: 9.3, region: '法国',
    description: '瘫痪富翁与黑人护工跨越种族与阶级的友谊。真实故事改编，笑中带泪的法国票房奇迹，温暖了全世界。',
    quote: '他没有同情心，这正是我想要的。',
    image: 'images/m013.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241197/sid/1/nid/1.html',
  },
  {
    id: 'm014', rank: 14, title: '疯狂动物城', originalTitle: 'Zootopia', year: 2016,
    director: '拜伦·霍华德 / 里奇·摩尔', cast: ['金妮弗·古德温', '杰森·贝特曼', '伊德里斯·艾尔巴', '珍妮·斯蕾特'],
    categories: ['动画', '冒险', '喜剧'], rating: 9.2, region: '美国',
    description: '兔子朱迪进城追梦当警察，与狐狸尼克联手破案。迪士尼用动物乌托邦讲种族偏见，树懒闪电成为永恒笑点。',
    quote: '在动物城，任何人都能成为自己想成为的样子。',
    image: 'images/m014.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/14172/sid/1/nid/1.html',
  },
  {
    id: 'm015', rank: 15, title: '三块广告牌', originalTitle: 'Three Billboards Outside Ebbing, Missouri', year: 2017,
    director: '马丁·麦克唐纳', cast: ['弗兰西斯·麦克多蒙德', '伍迪·哈里森', '山姆·洛克威尔', '艾比·考尼什'],
    categories: ['剧情', '犯罪'], rating: 8.9, region: '美国',
    description: '母亲租下三块广告牌向不作为的警方施压寻找杀女凶手。愤怒与救赎在黑色幽默中交织，科恩嫂封神之作。',
    quote: '愤怒只会招致更大的愤怒。',
    image: 'images/m015.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/225862/sid/1/nid/1.html',
  },
  {
    id: 'm016', rank: 16, title: '放牛班的春天', originalTitle: 'Les Choristes', year: 2004,
    director: '克里斯托夫·巴拉蒂', cast: ['热拉尔·朱尼奥', '让-巴蒂斯特·莫尼耶', '弗朗索瓦·贝莱昂', '凯德·麦拉德'],
    categories: ['剧情', '音乐'], rating: 9.3, region: '法国',
    description: '音乐老师马修用合唱团感化一群问题少年，发现了天籁之音莫翰奇。童声合唱《眺望你的路途》穿透灵魂。',
    quote: '永远不要说永远，总有东西值得尝试。',
    image: 'images/m016.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241190/sid/1/nid/1.html',
  },
  {
    id: 'm017', rank: 17, title: '小丑', originalTitle: 'Joker', year: 2019,
    director: '托德·菲利普斯', cast: ['华金·菲尼克斯', '罗伯特·德尼罗', '莎姬·贝兹', '弗兰西丝·康罗伊'],
    categories: ['剧情', '犯罪', '惊悚'], rating: 8.7, region: '美国',
    description: '亚瑟·弗莱克从被社会碾压的边缘人蜕变为哥谭混乱的象征。华金以45公斤之躯摘下威尼斯金狮和奥斯卡影帝。',
    quote: '我曾以为我的人生是一场悲剧，现在我发现，其实是一场喜剧。',
    image: 'images/m017.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/248062/sid/1/nid/1.html',
  },
  {
    id: 'm018', rank: 18, title: '忠犬八公的故事', originalTitle: "Hachi: A Dog's Tale", year: 2009,
    director: '拉斯·霍尔斯道姆', cast: ['理查·基尔', '萨拉·罗默尔', '琼·艾伦', '杰森·亚历山大'],
    categories: ['剧情', '家庭'], rating: 9.3, region: '美国',
    description: '秋田犬八公每天到车站等主人下班，主人在校突发去世后再也没回来，八公一等就是十年直到生命终点。',
    quote: '它教会了我们忠诚的含义——永远不要忘记你所爱的人。',
    image: 'images/m018.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/18660/sid/1/nid/1.html',
  },
  {
    id: 'm019', rank: 19, title: '绿皮书', originalTitle: 'Green Book', year: 2018,
    director: '彼得·法雷里', cast: ['维果·莫滕森', '马赫沙拉·阿里', '琳达·卡德里尼', '塞巴斯蒂安·马尼斯科'],
    categories: ['剧情', '喜剧', '传记'], rating: 9.0, region: '美国',
    description: '意大利裔混混司机与黑人钢琴家南下巡演，在种族隔离的南方结下跨越肤色与阶级的真挚友谊。奥斯卡最佳影片。',
    quote: '世界上有太多孤独的人，害怕先踏出第一步。',
    image: 'images/m019.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241156/sid/1/nid/1.html',
  },
  {
    id: 'm020', rank: 20, title: '何以为家', originalTitle: 'Capernaum', year: 2018,
    director: '娜丁·拉巴基', cast: ['赞恩·阿尔·拉菲亚', '约丹诺斯·希费罗', '博鲁瓦蒂夫·特雷杰·班科尔', '卡萨尔·艾尔·哈达德'],
    categories: ['剧情'], rating: 9.1, region: '黎巴嫩',
    description: '12岁男孩赞恩将父母告上法庭，罪名是"生下了他"。真实难民儿童的纪实演绎，叩问没有能力抚养为何要生养。',
    quote: '我要起诉我的父母，因为他们生下了我。',
    image: 'images/m020.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/19925/sid/1/nid/1.html',
  },

  // ====================== Top 21-30 ======================
  {
    id: 'm021', rank: 21, title: '社交网络', originalTitle: 'The Social Network', year: 2010,
    director: '大卫·芬奇', cast: ['杰西·艾森伯格', '安德鲁·加菲尔德', '贾斯汀·汀布莱克', '艾米·汉莫'],
    categories: ['剧情', '传记'], rating: 8.8, region: '美国',
    description: '马克·扎克伯格创建Facebook的历程，天才与背叛交织的现代寓言。大卫·芬奇用冰冷色调勾勒出数字时代的孤独。',
    quote: '你不是一个混蛋，马克，你只是太努力在成为一个混蛋。',
    image: 'images/m021.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/248293/sid/1/nid/1.html',
  },
  {
    id: 'm022', rank: 22, title: '少年派的奇幻漂流', originalTitle: 'Life of Pi', year: 2012,
    director: '李安', cast: ['苏拉·沙玛', '伊尔凡·可汗', '拉菲·斯波', '阿迪勒·侯赛因'],
    categories: ['奇幻', '冒险', '剧情'], rating: 9.1, region: '美国',
    description: '印度少年派与孟加拉虎理查德·帕克在太平洋上漂流227天。李安用3D视觉奇观讲述关于信仰与生存的寓言。',
    quote: '人生就是不断地放下，然而痛心的是，我还没来得及与你好好告别。',
    image: 'images/m022.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/240602/sid/1/nid/1.html',
  },
  {
    id: 'm023', rank: 23, title: '你的名字。', originalTitle: 'Your Name.', year: 2016,
    director: '新海诚', cast: ['神木隆之介', '上白石萌音', '长泽雅美', '市原悦子'],
    categories: ['动画', '爱情', '奇幻'], rating: 8.9, region: '日本',
    description: '东京男生泷与乡下女生三叶在梦中互换身体，跨越时空的爱恋在彗星降临之夜达到高潮。新海诚现象级作品。',
    quote: '无论你在世界的哪个角落，我都会去见你。',
    image: 'images/m023.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/183649/sid/1/nid/1.html',
  },
  {
    id: 'm024', rank: 24, title: '让子弹飞', originalTitle: 'Let the Bullets Fly', year: 2010,
    director: '姜文', cast: ['姜文', '周润发', '葛优', '刘嘉玲'],
    categories: ['动作', '喜剧', '剧情'], rating: 9.1, region: '中国',
    description: '北洋年间土匪张麻子劫持县长马邦德后冒充上任，与恶霸黄四郎展开智斗。姜文用黑色幽默解构权力与革命。',
    quote: '让子弹飞一会儿。',
    image: 'images/m024.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/14297/sid/1/nid/1.html',
  },
  {
    id: 'm025', rank: 25, title: '哈利·波特与魔法石', originalTitle: "Harry Potter and the Philosopher's Stone", year: 2001,
    director: '克里斯·哥伦布', cast: ['丹尼尔·雷德克里夫', '艾玛·沃特森', '鲁伯特·格林特', '理查德·哈里斯'],
    categories: ['奇幻', '冒险', '家庭'], rating: 9.1, region: '英国',
    description: '11岁的哈利收到霍格沃茨录取通知书，踏入魔法世界的开端。J.K.罗琳缔造的魔法宇宙从这里启航，陪伴一代人成长。',
    quote: '决定我们成为什么样的人的，不是我们的能力，而是我们的选择。',
    image: 'images/m025.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/199677/sid/1/nid/1.html',
  },
  {
    id: 'm026', rank: 26, title: '楚门的世界', originalTitle: 'The Truman Show', year: 2000,
    director: '彼得·威尔', cast: ['金·凯瑞', '劳拉·琳妮', '艾德·哈里斯', '诺亚·艾默里奇'],
    categories: ['剧情', '科幻'], rating: 9.3, region: '美国',
    description: '楚门从出生起就生活在全球直播的巨大摄影棚中而不自知。当他开始怀疑周围的一切，一场震撼世界的越狱展开了。',
    quote: '如果再也见不到你，祝你早安、午安、晚安。',
    image: 'images/m026.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/25086/sid/1/nid/1.html',
  },
  {
    id: 'm027', rank: 27, title: '我不是药神', originalTitle: 'Dying to Survive', year: 2018,
    director: '文牧野', cast: ['徐峥', '王传君', '周一围', '谭卓'],
    categories: ['剧情', '喜剧'], rating: 9.0, region: '中国',
    description: '保健品店老板程勇从走私印度仿制药牟利到自掏腰包救人。真人真事改编，推动了中国医保改革的现实题材力作。',
    quote: '这世界上只有一种病，穷病。',
    image: 'images/m027.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/214226/sid/1/nid/1.html',
  },
  {
    id: 'm028', rank: 28, title: '花样年华', originalTitle: 'In the Mood for Love', year: 2000,
    director: '王家卫', cast: ['梁朝伟', '张曼玉', '潘迪华', '萧炳林'],
    categories: ['爱情', '剧情'], rating: 8.8, region: '中国',
    description: '1962年香港，两对夫妻成为邻居，周慕云与苏丽珍发现各自配偶出轨后，在克制与暧昧中演绎最性感的未竟之恋。',
    quote: '如果多一张船票，你会不会跟我走？',
    image: 'images/m028.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/240949/sid/1/nid/1.html',
  },
  {
    id: 'm029', rank: 29, title: '阿凡达', originalTitle: 'Avatar', year: 2009,
    director: '詹姆斯·卡梅隆', cast: ['萨姆·沃辛顿', '佐伊·索尔达娜', '西格妮·韦弗', '史蒂芬·朗'],
    categories: ['科幻', '冒险', '动作'], rating: 8.8, region: '美国',
    description: '前海军陆战队员杰克进入潘多拉星球纳美族身体，在人类贪婪与土著文明之间做出选择。卡梅隆重新定义了3D电影。',
    quote: 'I see you. 我看见了你。',
    image: 'images/m029.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/220681/sid/1/nid/1.html',
  },
  {
    id: 'm030', rank: 30, title: '窃听风暴', originalTitle: 'Das Leben der Anderen', year: 2006,
    director: '弗洛里安·亨克尔·冯·多纳斯马', cast: ['乌尔里希·穆埃', '塞巴斯蒂安·科赫', '马蒂娜·格德克', '乌尔里希·图库尔'],
    categories: ['剧情', '悬疑', '惊悚'], rating: 9.2, region: '德国',
    description: '1984年东德秘密警察监听剧作家，却被艺术与人性打动选择默默守护。献给我那本好人的书——结尾一句话泪崩。',
    quote: '这是献给我的那本书。',
    image: 'images/m030.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241129/sid/1/nid/1.html',
  },

  // ====================== Top 31-40 ======================
  {
    id: 'm031', rank: 31, title: '当幸福来敲门', originalTitle: 'The Pursuit of Happyness', year: 2006,
    director: '加布里埃莱·穆奇诺', cast: ['威尔·史密斯', '贾登·史密斯', '桑迪·牛顿', '布莱恩·豪威'],
    categories: ['剧情', '传记', '家庭'], rating: 9.1, region: '美国',
    description: '落魄推销员克里斯带着儿子流浪街头仍坚持追求股票经纪人梦想。地铁厕所过夜那段，父爱让所有人心碎又振作。',
    quote: '别让别人告诉你，你成不了才。',
    image: 'images/m031.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239733/sid/1/nid/1.html',
  },
  {
    id: 'm032', rank: 32, title: '钢铁侠', originalTitle: 'Iron Man', year: 2008,
    director: '乔恩·费儒', cast: ['小罗伯特·唐尼', '格温妮丝·帕特洛', '杰夫·布里吉斯', '泰伦斯·霍华德'],
    categories: ['动作', '科幻', '冒险'], rating: 8.7, region: '美国',
    description: '军火商托尼·斯塔克被绑架后造出钢铁战衣逃生，从此以凡人之躯比肩神明。MCU开山之作，唐尼一己之力开启漫威宇宙。',
    quote: '我是钢铁侠。',
    image: 'images/m032.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/5539/sid/1/nid/1.html',
  },
  {
    id: 'm033', rank: 33, title: '鬼子来了', originalTitle: 'Devils on the Doorstep', year: 2000,
    director: '姜文', cast: ['姜文', '姜宏波', '香川照之', '袁丁'],
    categories: ['剧情', '战争', '喜剧'], rating: 9.3, region: '中国',
    description: '抗战末期华北农村，村民马大三被塞了一个日本俘虏和翻译，在荒诞与残酷间所有人性暴露无遗。姜文迄今最伟大的电影。',
    quote: '我一手一个掐巴死俩，刨坑埋了。',
    image: 'images/m033.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239520/sid/1/nid/1.html',
  },
  {
    id: 'm034', rank: 34, title: '奥本海默', originalTitle: 'Oppenheimer', year: 2023,
    director: '克里斯托弗·诺兰', cast: ['基里安·墨菲', '艾米莉·布朗特', '马特·达蒙', '小罗伯特·唐尼'],
    categories: ['传记', '剧情', '历史'], rating: 8.9, region: '美国',
    description: '原子弹之父奥本海默领导曼哈顿计划，在创造人类最强武器的同时也开启了道德深渊。诺兰以IMAX黑白影像呈现毁灭与良知。',
    quote: '现在我成了死神，世界的毁灭者。',
    image: 'images/m034.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/246610/sid/1/nid/1.html',
  },
  {
    id: 'm035', rank: 35, title: 'V字仇杀队', originalTitle: 'V for Vendetta', year: 2005,
    director: '詹姆斯·麦克特格', cast: ['娜塔莉·波特曼', '雨果·维文', '斯蒂芬·瑞', '约翰·赫特'],
    categories: ['动作', '剧情', '科幻'], rating: 8.9, region: '美国',
    description: '戴盖伊·福克斯面具的神秘人V在极权英国掀起革命风暴。面具成为全球抗议运动的符号，思想是防弹的宣言。',
    quote: '面具之下是思想，而思想——是杀不死的。',
    image: 'images/m035.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/186608/sid/1/nid/1.html',
  },
  {
    id: 'm036', rank: 36, title: '心灵捕手', originalTitle: 'Good Will Hunting', year: 2000,
    director: '格斯·范·桑特', cast: ['马特·达蒙', '罗宾·威廉姆斯', '本·阿弗莱克', '明妮·德瑞弗'],
    categories: ['剧情'], rating: 8.9, region: '美国',
    description: '天才清洁工威尔在数学教授和心理医生帮助下走出童年阴影。湖边长椅上的对话"这不是你的错"——治愈了整个世界。',
    quote: '这不是你的错。',
    image: 'images/m036.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/14157/sid/1/nid/1.html',
  },
  {
    id: 'm037', rank: 37, title: '哈利·波特与死亡圣器（下）', originalTitle: 'Harry Potter and the Deathly Hallows: Part 2', year: 2011,
    director: '大卫·叶茨', cast: ['丹尼尔·雷德克里夫', '艾玛·沃特森', '鲁伯特·格林特', '艾伦·瑞克曼'],
    categories: ['奇幻', '冒险', '动作'], rating: 9.1, region: '英国',
    description: '哈利与伏地魔在霍格沃茨迎来最终决战。斯内普的记忆揭开"Always"的真相，十年魔法史诗以泪目收尾。',
    quote: 'After all this time? — Always.',
    image: 'images/m037.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/200998/sid/1/nid/1.html',
  },
  {
    id: 'm038', rank: 38, title: '头脑特工队', originalTitle: 'Inside Out', year: 2015,
    director: '彼特·道格特', cast: ['艾米·波勒', '菲利丝·史密斯', '刘易斯·布莱克', '敏迪·卡灵'],
    categories: ['动画', '冒险', '喜剧'], rating: 8.8, region: '美国',
    description: '小女孩莱莉脑中的五种情绪小人——乐乐、忧忧、怒怒、怕怕、厌厌，在搬家后的混乱中学会接纳所有情绪的成长寓言。',
    quote: '哭泣能让我慢下来，不再被生活的重压所困扰。',
    image: 'images/m038.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/244730/sid/1/nid/1.html',
  },
  {
    id: 'm039', rank: 39, title: '消失的爱人', originalTitle: 'Gone Girl', year: 2014,
    director: '大卫·芬奇', cast: ['本·阿弗莱克', '裴淳华', '尼尔·帕特里克·哈里斯', '凯莉·库恩'],
    categories: ['悬疑', '犯罪', '剧情'], rating: 8.8, region: '美国',
    description: '结婚五周年妻子失踪，丈夫成为头号嫌疑人。大卫·芬奇以手术刀般精准的叙事剖开婚姻中最阴暗的真相。',
    quote: '完美的妻子，完美的复仇。',
    image: 'images/m039.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/230635/sid/1/nid/1.html',
  },
  {
    id: 'm040', rank: 40, title: '布达佩斯大饭店', originalTitle: 'The Grand Budapest Hotel', year: 2014,
    director: '韦斯·安德森', cast: ['拉尔夫·费因斯', '托尼·雷沃罗利', '阿德里安·布洛迪', '威廉·达福'],
    categories: ['喜剧', '剧情', '冒险'], rating: 8.9, region: '美国',
    description: '布达佩斯大饭店大堂经理古斯塔夫与门童零卷入遗产争夺与谋杀案。韦斯·安德森极致对称构图与粉色美学巅峰之作。',
    quote: '在野蛮的屠宰场上，还是有些文明的微光存在。',
    image: 'images/m040.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239734/sid/1/nid/1.html',
  },

  // ====================== Top 41-50 ======================
  {
    id: 'm041', rank: 41, title: '玩具总动员3', originalTitle: 'Toy Story 3', year: 2010,
    director: '李·昂克里奇', cast: ['汤姆·汉克斯', '蒂姆·艾伦', '琼·库萨克', '尼德·巴蒂'],
    categories: ['动画', '冒险', '喜剧'], rating: 8.9, region: '美国',
    description: '安迪要去上大学了，玩具们误入幼儿园经历一场惊心动魄的大逃亡。焚烧炉那一幕让整个影厅的成年人都哭成孩子。',
    quote: '谢谢你们，陪我走过童年。',
    image: 'images/m041.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/24702/sid/1/nid/1.html',
  },
  {
    id: 'm042', rank: 42, title: '杀人回忆', originalTitle: 'Memories of Murder', year: 2003,
    director: '奉俊昊', cast: ['宋康昊', '金相庆', '金雷夏', '宋在浩'],
    categories: ['悬疑', '犯罪', '剧情'], rating: 8.9, region: '韩国',
    description: '1986年韩国小镇连环杀人案，两个刑警以截然不同的方式追凶。奉俊昊的成名作，结尾凝视镜头刺穿每一个观众的良知。',
    quote: '你看起来很普通。',
    image: 'images/m042.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/242219/sid/1/nid/1.html',
  },
  {
    id: 'm043', rank: 43, title: '被嫌弃的松子的一生', originalTitle: 'Memories of Matsuko', year: 2006,
    director: '中岛哲也', cast: ['中谷美纪', '瑛太', '香川照之', '市川实日子'],
    categories: ['剧情', '音乐', '喜剧'], rating: 8.9, region: '日本',
    description: '松子一生都在渴望被爱，却一次次被抛弃伤害，最后孤独离世。中岛哲也用绚烂歌舞包装最悲凉的人生，灿烂到令人心碎。',
    quote: '生而在世，我很抱歉。',
    image: 'images/m043.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/22024/sid/1/nid/1.html',
  },
  {
    id: 'm044', rank: 44, title: '谍影重重3', originalTitle: 'The Bourne Ultimatum', year: 2007,
    director: '保罗·格林格拉斯', cast: ['马特·达蒙', '朱丽娅·斯蒂尔斯', '大卫·斯特雷泽恩', '斯科特·格伦'],
    categories: ['动作', '悬疑', '惊悚'], rating: 8.9, region: '美国',
    description: '杰森·伯恩终于逼近自己身份的终极真相。手持摄影+凌厉剪辑定义了现代特工动作片的新标杆，全程无尿点。',
    quote: '看着我，你到底看到了什么？',
    image: 'images/m044.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/18762/sid/1/nid/1.html',
  },
  {
    id: 'm045', rank: 45, title: '天使爱美丽', originalTitle: 'Amélie', year: 2001,
    director: '让-皮埃尔·热内', cast: ['奥黛丽·塔图', '马修·卡索维茨', '贾梅尔·杜布兹', '多米尼克·皮侬'],
    categories: ['喜剧', '爱情', '奇幻'], rating: 8.8, region: '法国',
    description: '古灵精怪的巴黎女孩艾米丽偷偷帮助身边人获得幸福，最终也找到自己的真爱。让-皮埃尔·热内用童话色彩涂满巴黎每个角落。',
    quote: '如果没有你，良辰美景更与何人说。',
    image: 'images/m045.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/22083/sid/1/nid/1.html',
  },
  {
    id: 'm046', rank: 46, title: '致命魔术', originalTitle: 'The Prestige', year: 2006,
    director: '克里斯托弗·诺兰', cast: ['克里斯蒂安·贝尔', '休·杰克曼', '斯嘉丽·约翰逊', '迈克尔·凯恩'],
    categories: ['悬疑', '科幻', '剧情'], rating: 8.8, region: '美国',
    description: '两位魔术师不惜一切代价相互超越，从舞台表演滑向致命深渊。诺兰用三层嵌套叙事完成了一场关于牺牲与执念的伟大魔术。',
    quote: '你想找出秘密，但你不去寻找，你想要被欺骗。',
    image: 'images/m046.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239536/sid/1/nid/1.html',
  },
  {
    id: 'm047', rank: 47, title: '七武士', originalTitle: 'Seven Samurai', year: 2000,
    director: '黑泽明', cast: ['三船敏郎', '志村乔', '津岛惠子', '岛崎雪子'],
    categories: ['动作', '剧情', '历史'], rating: 9.3, region: '日本',
    description: '战国时代农民雇佣七名武士保卫村庄免遭山贼劫掠。黑泽明以史诗篇幅描绘人性。注：本数据以修复版2000年重映时间计。',
    quote: '仗打赢了，但赢的是那些农民，不是我们。',
    image: 'images/m047.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/243600/sid/1/nid/1.html',
  },
  {
    id: 'm048', rank: 48, title: '闪灵', originalTitle: 'The Shining', year: 2000,
    director: '斯坦利·库布里克', cast: ['杰克·尼科尔森', '谢莉·杜瓦尔', '丹尼·劳埃德', '斯加特曼·克罗索斯'],
    categories: ['恐怖', '悬疑', '剧情'], rating: 8.7, region: '美国',
    description: '作家杰克携家人看守冬季无人酒店，在孤独与超自然力量中逐渐疯狂。库布里克式恐惧三十年后仍令人毛骨悚然。注：以2000年后数字修复版计入。',
    quote: 'Here\'s Johnny!',
    image: 'images/m048.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/19127/sid/1/nid/1.html',
  },
  {
    id: 'm049', rank: 49, title: '辩护人', originalTitle: 'The Attorney', year: 2013,
    director: '杨宇硕', cast: ['宋康昊', '金英爱', '吴达洙', '郭度沅'],
    categories: ['剧情', '传记', '历史'], rating: 9.2, region: '韩国',
    description: '穷律师宋佑硕从只认钱到为民主运动学生挺身辩护。以韩国前总统卢武铉为原型，宋康昊炸裂演技成就韩国民主史诗。',
    quote: '岩石再坚硬也是死的，鸡蛋再脆弱也是活的。',
    image: 'images/m049.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239474/sid/1/nid/1.html',
  },
  {
    id: 'm050', rank: 50, title: '钢琴家', originalTitle: 'The Pianist', year: 2002,
    director: '罗曼·波兰斯基', cast: ['阿德里安·布洛迪', '托马斯·克莱舒曼', '艾米莉娅·福克斯', '米哈乌·热布罗夫斯基'],
    categories: ['剧情', '战争', '传记', '音乐'], rating: 9.2, region: '英国',
    description: '犹太钢琴家在华沙废墟中艰难求生，一位德国军官的善意让他熬到解放。阿德里安·布洛迪凭此片成为最年轻奥斯卡影帝。',
    quote: '我不知道那是什么，但我知道那很美。',
    image: 'images/m050.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241185/sid/1/nid/1.html',
  },

  // ====================== Top 51-60 ======================
  {
    id: 'm051', rank: 51, title: '降临', originalTitle: 'Arrival', year: 2016,
    director: '丹尼斯·维伦纽瓦', cast: ['艾米·亚当斯', '杰瑞米·雷纳', '福里斯特·惠特克', '迈克尔·斯图巴'],
    categories: ['科幻', '剧情', '悬疑'], rating: 8.7, region: '美国',
    description: '语言学家露易丝尝试与外星生物沟通，在学习七肢桶语言的过程中获得了预知未来的能力。维伦纽瓦用语言学重构时间观。',
    quote: '即使知道结局，我还是会选择拥抱每一个瞬间。',
    image: 'images/m051.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/250276/sid/1/nid/1.html',
  },
  {
    id: 'm052', rank: 52, title: '沉默的羔羊', originalTitle: 'The Silence of the Lambs', year: 2001,
    director: '乔纳森·戴米', cast: ['朱迪·福斯特', '安东尼·霍普金斯', '斯科特·格伦', '泰德·拉文'],
    categories: ['犯罪', '悬疑', '惊悚'], rating: 8.9, region: '美国',
    description: '见习特工克拉丽丝求助于食人魔汉尼拔博士追查连环杀手比尔。霍普金斯仅16分钟出镜便拿下奥斯卡影帝。注：以2001年特别版计算。',
    quote: '曾经有个调查员想测试我，我就着他的蚕豆配红酒吃掉了他的肝脏。',
    image: 'images/m052.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/240973/sid/1/nid/1.html',
  },
  {
    id: 'm053', rank: 53, title: '地球上的星星', originalTitle: 'Taare Zameen Par', year: 2007,
    director: '阿米尔·汗', cast: ['阿米尔·汗', '达席尔·萨法瑞', '塔奈·切赫达', '萨谢·英吉尼尔'],
    categories: ['剧情', '家庭'], rating: 8.9, region: '印度',
    description: '有阅读障碍的8岁男孩伊桑在寄宿学校遇到美术老师尼克，后者发现了伊桑的绘画天才。每个孩子都是地球上的星星。',
    quote: '每一个孩子都是独一无二的，他们迟早会以自己的方式发光。',
    image: 'images/m053.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/3182/sid/1/nid/1.html',
  },
  {
    id: 'm054', rank: 54, title: '黑天鹅', originalTitle: 'Black Swan', year: 2010,
    director: '达伦·阿伦诺夫斯基', cast: ['娜塔莉·波特曼', '米拉·库尼斯', '文森特·卡索', '薇诺娜·瑞德'],
    categories: ['剧情', '惊悚', '悬疑'], rating: 8.7, region: '美国',
    description: '芭蕾舞者妮娜为演绎黑白天鹅走向精神分裂的边缘。波特曼以肉体与灵魂的极致献祭摘下奥斯卡影后桂冠。',
    quote: '我感觉到了——完美。',
    image: 'images/m054.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/248640/sid/1/nid/1.html',
  },
  {
    id: 'm055', rank: 55, title: '爱乐之城', originalTitle: 'La La Land', year: 2016,
    director: '达米恩·查泽雷', cast: ['瑞恩·高斯林', '艾玛·斯通', '约翰·传奇', '罗丝玛丽·德薇特'],
    categories: ['爱情', '音乐', '剧情'], rating: 8.5, region: '美国',
    description: '爵士钢琴手与怀揣演员梦的女孩在洛杉矶相爱相励。最后那段蒙太奇"如果"让人心碎——有些人注定只能陪你走一程。',
    quote: '致那些做白日梦的人，虽然看起来那么傻。',
    image: 'images/m055.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/14467/sid/1/nid/1.html',
  },
  {
    id: 'm056', rank: 56, title: '断背山', originalTitle: 'Brokeback Mountain', year: 2005,
    director: '李安', cast: ['希斯·莱杰', '杰克·吉伦哈尔', '米歇尔·威廉姆斯', '安妮·海瑟薇'],
    categories: ['爱情', '剧情'], rating: 8.8, region: '美国',
    description: '1963年怀俄明州，两个牛仔在断背山上燃起一生无法熄灭的爱火。李安用东方式含蓄拍出了西方最刻骨铭心的同性恋曲。',
    quote: 'I wish I knew how to quit you.',
    image: 'images/m056.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239471/sid/1/nid/1.html',
  },
  {
    id: 'm057', rank: 57, title: '剪刀手爱德华', originalTitle: 'Edward Scissorhands', year: 2000,
    director: '蒂姆·波顿', cast: ['约翰尼·德普', '薇诺娜·瑞德', '黛安·韦斯特', '安东尼·迈克尔·豪尔'],
    categories: ['爱情', '奇幻', '剧情'], rating: 8.7, region: '美国',
    description: '双手是剪刀的机器人爱德华被带到小镇，他用剪刀创造美，也因剪刀被世人误解。注：以2000年导演剪辑版计入。',
    quote: '如果我没有剪刀，就不能保护你；如果我有剪刀，就不能拥抱你。',
    image: 'images/m057.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/23064/sid/1/nid/1.html',
  },
  {
    id: 'm058', rank: 58, title: '海边的曼彻斯特', originalTitle: 'Manchester by the Sea', year: 2016,
    director: '肯尼斯·罗纳根', cast: ['卡西·阿弗莱克', '卢卡斯·赫奇斯', '米歇尔·威廉姆斯', '凯尔·钱德勒'],
    categories: ['剧情', '家庭'], rating: 8.7, region: '美国',
    description: '李·钱德勒因哥哥去世回到故乡照顾侄子，往事如潮水般涌来。卡西·阿弗莱克用沉默与隐忍演出了无法被治愈的悲伤。',
    quote: 'I can\'t beat it.',
    image: 'images/m058.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239518/sid/1/nid/1.html',
  },
  {
    id: 'm059', rank: 59, title: '驯龙高手', originalTitle: 'How to Train Your Dragon', year: 2010,
    director: '迪恩·德布洛斯 / 克里斯·桑德斯', cast: ['杰伊·巴鲁切尔', '杰拉德·巴特勒', '克雷格·费格森', '亚美莉卡·费雷拉'],
    categories: ['动画', '冒险', '家庭'], rating: 8.8, region: '美国',
    description: '维京少年小嗝嗝与夜煞龙无牙从敌对到成为生死搭档，打破人与龙的千年对立。Toothless萌翻全宇宙，友情跨越物种。',
    quote: '真正的勇气不是没有恐惧，而是直面恐惧。',
    image: 'images/m059.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241005/sid/1/nid/1.html',
  },
  {
    id: 'm060', rank: 60, title: '功夫', originalTitle: 'Kung Fu Hustle', year: 2004,
    director: '周星驰', cast: ['周星驰', '元秋', '元华', '黄圣依'],
    categories: ['动作', '喜剧', '奇幻'], rating: 8.8, region: '中国',
    description: '混混阿星误闯猪笼城寨，揭开隐藏高手们的传奇对决。周星驰集大成之作，包租婆、斧头帮舞成为华语电影永恒的经典画面。',
    quote: '一支穿云箭，千军万马来相见。',
    image: 'images/m060.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/248500/sid/1/nid/1.html',
  },

  // ====================== Top 61-70 ======================
  {
    id: 'm061', rank: 61, title: '蝙蝠侠：黑暗骑士崛起', originalTitle: 'The Dark Knight Rises', year: 2012,
    director: '克里斯托弗·诺兰', cast: ['克里斯蒂安·贝尔', '汤姆·哈迪', '安妮·海瑟薇', '约瑟夫·高登-莱维特'],
    categories: ['动作', '犯罪', '剧情'], rating: 8.7, region: '美国',
    description: '布鲁斯·韦恩从隐退中归来对抗贝恩，哥谭市面临核弹危机。诺兰蝙蝠侠三部曲史诗终章，英雄可以被打倒但绝不会被击败。',
    quote: '英雄可以是任何人，即使只是做一件简单的事。',
    image: 'images/m061.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/210601/sid/1/nid/1.html',
  },
  {
    id: 'm062', rank: 62, title: '树上的男爵', originalTitle: 'The Tree of Life', year: 2011,
    director: '泰伦斯·马力克', cast: ['布拉德·皮特', '西恩·潘', '杰西卡·查斯坦', '亨特·麦奎肯'],
    categories: ['剧情', '奇幻'], rating: 8.2, region: '美国',
    description: '从宇宙诞生到生命终结，从德州家庭往事到灵魂的终极拷问。马力克以神性镜头追问上帝、自然与恩典。戛纳金棕榈争议之作。',
    quote: '自然只求愉悦自己。',
    image: 'images/m062.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/235081/sid/1/nid/1.html',
  },
  {
    id: 'm063', rank: 63, title: '新世界', originalTitle: 'New World', year: 2013,
    director: '朴勋政', cast: ['李政宰', '崔岷植', '黄政民', '宋智孝'],
    categories: ['犯罪', '剧情', '动作'], rating: 8.9, region: '韩国',
    description: '卧底警察李子成在黑帮老大死后陷入了身份与忠诚的两难。韩国版《无间道》，电梯战神一战封神，结局震撼人心。',
    quote: '你以为你在选择，其实你早就没有选择了。',
    image: 'images/m063.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/251072/sid/1/nid/1.html',
  },
  {
    id: 'm064', rank: 64, title: '阳光姐妹淘', originalTitle: 'Sunny', year: 2011,
    director: '姜炯哲', cast: ['沈恩京', '闵孝琳', '姜素拉', '南宝拉'],
    categories: ['剧情', '喜剧'], rating: 8.8, region: '韩国',
    description: '中年主妇寻找失散25年的高中闺蜜团Sunny成员，青春回忆与中年现实交织。笑着笑着就哭了，关于友谊的最好电影。',
    quote: '我们，以后也在一起，一直在一起。',
    image: 'images/m064.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/217155/sid/1/nid/1.html',
  },
  {
    id: 'm065', rank: 65, title: '银翼杀手2049', originalTitle: 'Blade Runner 2049', year: 2017,
    director: '丹尼斯·维伦纽瓦', cast: ['瑞恩·高斯林', '哈里森·福特', '安娜·德·阿玛斯', '杰瑞德·莱托'],
    categories: ['科幻', '悬疑', '剧情'], rating: 8.5, region: '美国',
    description: '复制人K在追查埋藏三十年的秘密时逐渐逼近关于自身身份的真相。维伦纽瓦以极致视觉美学重构赛博朋克世界。',
    quote: '为正确的原因死去，是我们能做的最具人性的事。',
    image: 'images/m065.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/20223/sid/1/nid/1.html',
  },
  {
    id: 'm066', rank: 66, title: '看不见的客人', originalTitle: 'Contratiempo', year: 2016,
    director: '奥里奥尔·保罗', cast: ['马里奥·卡萨斯', '阿娜·瓦格纳', '何塞·科罗纳多', '巴巴拉·莱涅'],
    categories: ['悬疑', '犯罪', '惊悚'], rating: 8.8, region: '西班牙',
    description: '企业家被指控谋杀情人，金牌女律师与他展开180分钟的心理博弈。43处反转，最后一刻颠覆所有认知的悬疑教科书。',
    quote: '真相并不复杂，真正复杂的是谎言。',
    image: 'images/m066.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/48732/sid/1/nid/1.html',
  },
  {
    id: 'm067', rank: 67, title: '瞬息全宇宙', originalTitle: 'Everything Everywhere All at Once', year: 2022,
    director: '关家永 / 丹尼尔·施纳特', cast: ['杨紫琼', '关继威', '许玮伦', '杰米·李·柯蒂斯'],
    categories: ['科幻', '冒险', '喜剧'], rating: 8.3, region: '美国',
    description: '华裔洗衣店大妈穿越多元宇宙拯救世界。天马行空的想象力包裹关于母女和解、家庭接纳的温暖内核，横扫奥斯卡七项大奖。',
    quote: '在所有宇宙中，我都想和你一起。',
    image: 'images/m067.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/40006/sid/1/nid/1.html',
  },
  {
    id: 'm068', rank: 68, title: '老无所依', originalTitle: 'No Country for Old Men', year: 2007,
    director: '科恩兄弟', cast: ['汤米·李·琼斯', '哈维尔·巴登', '乔什·布洛林', '伍迪·哈里森'],
    categories: ['犯罪', '剧情', '惊悚'], rating: 8.7, region: '美国',
    description: '德州猎人偶然发现毒品交易现场的200万美金，引来冷血杀手安东一路追杀。科恩兄弟用沉默与偶然解构了西部片与命运。',
    quote: 'Call it, friendo.',
    image: 'images/m068.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/213029/sid/1/nid/1.html',
  },
  {
    id: 'm069', rank: 69, title: '调音师', originalTitle: 'Andhadhun', year: 2018,
    director: '斯里兰姆·拉格万', cast: ['阿尤斯曼·库拉纳', '塔布', '拉迪卡·艾普特', '安尔·德霍万'],
    categories: ['悬疑', '犯罪', '喜剧'], rating: 8.6, region: '印度',
    description: '假装盲人的钢琴师意外卷入一场谋杀案，从此陷入连环反转的命运漩涡。最后一秒的反转让所有人大呼过瘾。',
    quote: '说来话长，来杯咖啡？',
    image: 'images/m069.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/252178/sid/1/nid/1.html',
  },
  {
    id: 'm070', rank: 70, title: '疯狂的麦克斯4：狂暴之路', originalTitle: 'Mad Max: Fury Road', year: 2015,
    director: '乔治·米勒', cast: ['汤姆·哈迪', '查理兹·塞隆', '尼古拉斯·霍尔特', '休·基斯-拜恩'],
    categories: ['动作', '科幻', '冒险'], rating: 8.7, region: '澳大利亚',
    description: '末日废土中麦克斯与女战士弗瑞奥萨带领女奴们逃离暴君统治。两小时不间断追车狂潮，奥斯卡六项技术大奖封神。',
    quote: 'Oh, what a day! What a lovely day!',
    image: 'images/m070.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/36878/sid/1/nid/1.html',
  },

  // ====================== Top 71-80 ======================
  {
    id: 'm071', rank: 71, title: '大佛普拉斯', originalTitle: 'The Great Buddha +', year: 2017,
    director: '黄信尧', cast: ['陈竹昇', '庄益增', '戴立忍', '纳豆'],
    categories: ['剧情', '喜剧', '犯罪'], rating: 8.7, region: '中国台湾',
    description: '佛像工厂夜间保安菜埔与拾荒者肚财偷看老板行车记录仪，揭开权贵阶层的黑暗秘密。黑白影像下的底层悲歌与黑色幽默。',
    quote: '有钱人的人生果然是彩色的。',
    image: 'images/m071.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/225865/sid/1/nid/1.html',
  },
  {
    id: 'm072', rank: 72, title: '穆赫兰道', originalTitle: 'Mulholland Drive', year: 2001,
    director: '大卫·林奇', cast: ['娜奥米·沃茨', '劳拉·哈灵', '贾斯汀·塞洛克斯', '安·米勒'],
    categories: ['悬疑', '剧情', '惊悚'], rating: 8.5, region: '美国',
    description: '失忆女人与怀揣明星梦的女孩在洛杉矶寻找真相。大卫·林奇将好莱坞噩梦拍成了无法被剧透的迷幻恐怖寓言。',
    quote: 'No hay banda! 没有乐队！',
    image: 'images/m072.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/18118/sid/1/nid/1.html',
  },
  {
    id: 'm073', rank: 73, title: '摔跤吧！爸爸', originalTitle: 'Dangal', year: 2016,
    director: '尼特什·提瓦瑞', cast: ['阿米尔·汗', '法缇玛·萨那·纱卡', '桑亚·玛荷塔', '萨卡诗·泰瓦'],
    categories: ['剧情', '传记', '运动'], rating: 9.0, region: '印度',
    description: '前摔跤冠军将两个女儿训练成世界冠军的真实故事。阿米尔·汗先增重再减重，用社会议题包裹体育励志点燃印度女权之火。',
    quote: '你是我的骄傲。',
    image: 'images/m073.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241121/sid/1/nid/1.html',
  },
  {
    id: 'm074', rank: 74, title: '大鱼', originalTitle: 'Big Fish', year: 2003,
    director: '蒂姆·波顿', cast: ['伊万·麦克格雷格', '阿尔伯特·芬尼', '比利·克鲁德普', '杰西卡·兰格'],
    categories: ['奇幻', '剧情', '冒险'], rating: 8.8, region: '美国',
    description: '儿子试图在父亲临终前分辨他一生的夸张故事中哪些是真实的。蒂姆·波顿最温柔的作品，谎言有时比真相更接近生命本质。',
    quote: '一个人不停讲述自己的故事，他自己也就成了故事本身。',
    image: 'images/m074.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/249388/sid/1/nid/1.html',
  },
  {
    id: 'm075', rank: 75, title: '超脱', originalTitle: 'Detachment', year: 2011,
    director: '托尼·凯耶', cast: ['阿德里安·布洛迪', '马西娅·盖伊·哈登', '詹姆斯·肯恩', '克里斯蒂娜·亨德里克斯'],
    categories: ['剧情'], rating: 9.0, region: '美国',
    description: '代课老师亨利在一所问题高中经历了最压抑的三周。阿德里安·布洛迪的独白像钝刀割肉，剖开教育体系的崩坏与人性孤岛。',
    quote: '我们在失败中寻找成功的方法。',
    image: 'images/m075.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241201/sid/1/nid/1.html',
  },
  {
    id: 'm076', rank: 76, title: '三傻大闹宝莱坞', originalTitle: '3 Idiots', year: 2009,
    director: '拉库马·希拉尼', cast: ['阿米尔·汗', '卡琳娜·卡普', '马德哈万', '沙曼·乔希'],
    categories: ['喜剧', '剧情', '爱情'], rating: 9.2, region: '印度',
    description: '兰彻用打破常规的方式挑战僵化教育体制，寻找已失踪好友的旅程中揭开感人秘密。"All is well"成为一代人的精神图腾。',
    quote: '追求卓越，成功就会在不经意间追上你。',
    image: 'images/m076.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/218905/sid/1/nid/1.html',
  },
  {
    id: 'm077', rank: 77, title: '恐怖直播', originalTitle: 'The Terror Live', year: 2013,
    director: '金秉祐', cast: ['河正宇', '李璟荣', '全慧珍', '李大卫'],
    categories: ['悬疑', '犯罪', '剧情'], rating: 8.7, region: '韩国',
    description: '电台主播尹英华在直播中接到恐怖分子的炸弹威胁电话，为了收视率选择不报警。全程无尿点的单空间封闭惊悚神作。',
    quote: '我现在按下这个按钮，不是我一个人的问题。',
    image: 'images/m077.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/225839/sid/1/nid/1.html',
  },
  {
    id: 'm078', rank: 78, title: '贫民窟的百万富翁', originalTitle: 'Slumdog Millionaire', year: 2008,
    director: '丹尼·博伊尔', cast: ['戴夫·帕特尔', '芙蕾达·平托', '亚尼·卡普', '伊尔凡·可汗'],
    categories: ['剧情', '爱情'], rating: 8.7, region: '英国',
    description: '孟买贫民窟少年答对所有题目成为百万富翁，但被人怀疑作弊。每一道题的答案都对应他血泪交织的人生经历。奥斯卡最佳影片。',
    quote: '这是我们的命运。',
    image: 'images/m078.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/17652/sid/1/nid/1.html',
  },
  {
    id: 'm079', rank: 79, title: '素媛', originalTitle: 'Hope', year: 2013,
    director: '李濬益', cast: ['薛景求', '严志媛', '李甄', '金海淑'],
    categories: ['剧情', '家庭'], rating: 9.3, region: '韩国',
    description: '8岁女孩素媛遭遇性侵后，家人与邻居帮助她走出阴影的感人历程。真实事件改编，推动韩国修改法律，增加化学阉割条款。',
    quote: '最痛苦的不是身体的伤害，而是心灵。',
    image: 'images/m079.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/14864/sid/1/nid/1.html',
  },
  {
    id: 'm080', rank: 80, title: '这个男人来自地球', originalTitle: 'The Man from Earth', year: 2007,
    director: '理查德·沙因克曼', cast: ['大卫·李·史密斯', '托尼·托德', '约翰·比灵斯列', '艾伦·克劳福德'],
    categories: ['科幻', '剧情'], rating: 8.5, region: '美国',
    description: '大学教授约翰在告别派对上声称自己活了14000年。全片在一间客厅中完成，纯靠对话构建出一部宏大的人类文明史诗。',
    quote: '如果你活了一万四千年，宗教对你来说意味着什么？',
    image: 'images/m080.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239174/sid/1/nid/1.html',
  },

  // ====================== Top 81-90 ======================
  {
    id: 'm081', rank: 81, title: '战争之王', originalTitle: 'Lord of War', year: 2005,
    director: '安德鲁·尼科尔', cast: ['尼古拉斯·凯奇', '杰瑞德·莱托', '伊桑·霍克', '布丽姬·穆娜'],
    categories: ['剧情', '犯罪'], rating: 8.7, region: '美国',
    description: '军火贩子尤里从布鲁克林小混混成长为全球最大军火商。凯奇职业生涯最佳表演之一，开篇子弹的一生震撼开场。',
    quote: '有需求就有供给，这是经济学。',
    image: 'images/m081.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/39716/sid/1/nid/1.html',
  },
  {
    id: 'm082', rank: 82, title: '告白', originalTitle: 'Confessions', year: 2010,
    director: '中岛哲也', cast: ['松隆子', '冈田将生', '木村佳乃', '西井幸人'],
    categories: ['悬疑', '剧情', '犯罪'], rating: 8.8, region: '日本',
    description: '中学女教师发现女儿被班上学生杀害，在结业式上平静宣布了自己的复仇计划。极致冷冽的日式复仇美学，每一帧都扣人心弦。',
    quote: '开玩笑的。',
    image: 'images/m082.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/250425/sid/1/nid/1.html',
  },
  {
    id: 'm083', rank: 83, title: '达拉斯买家俱乐部', originalTitle: 'Dallas Buyers Club', year: 2013,
    director: '让-马克·瓦雷', cast: ['马修·麦康纳', '杰瑞德·莱托', '詹妮弗·加纳', '史蒂夫·扎恩'],
    categories: ['剧情', '传记'], rating: 8.8, region: '美国',
    description: '德州电工被确诊艾滋病后，走私未获批药物组建买家俱乐部自救和救他。麦康纳减重47斤，与莱托双双拿下奥斯卡双影帝。',
    quote: '我只想活着，这没什么好羞耻的。',
    image: 'images/m083.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/17330/sid/1/nid/1.html',
  },
  {
    id: 'm084', rank: 84, title: '爆裂鼓手', originalTitle: 'Whiplash', year: 2014,
    director: '达米恩·查泽雷', cast: ['迈尔斯·特勒', 'J·K·西蒙斯', '保罗·雷瑟', '梅丽莎·贝努瓦'],
    categories: ['剧情', '音乐'], rating: 8.7, region: '美国',
    description: '年轻鼓手在魔鬼导师的极致压迫下追求卓越。西蒙斯的"不是你妈教得好就是我教得好"成为银幕最令人窒息的教师形象。',
    quote: '英语里最害人的两个词就是"good job"。',
    image: 'images/m084.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239528/sid/1/nid/1.html',
  },
  {
    id: 'm085', rank: 85, title: '海豚湾', originalTitle: 'The Cove', year: 2009,
    director: '路易·西霍尤斯', cast: ['里克·欧巴瑞', '路易·西霍尤斯', '海顿·潘妮蒂尔', '伊莎贝尔·卢卡斯'],
    categories: ['纪录片'], rating: 9.3, region: '美国',
    description: '一支团队秘密拍摄日本太地町屠杀海豚的真相。奥斯卡最佳纪录片，海豚的血染红海湾的那一幕成为环保运动的标志性画面。',
    quote: '海豚的微笑是自然界最大的谎言。',
    image: 'images/m085.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/241178/sid/1/nid/1.html',
  },
  {
    id: 'm086', rank: 86, title: '荒蛮故事', originalTitle: 'Relatos Salvajes', year: 2014,
    director: '达米安·斯兹弗隆', cast: ['里卡多·达林', '莱昂纳多·斯巴拉格利亚', '艾丽卡·里瓦斯', '奥斯卡·马丁内斯'],
    categories: ['剧情', '喜剧', '犯罪'], rating: 8.8, region: '阿根廷',
    description: '六个关于复仇与失控的黑色短篇故事。从公路暴怒到婚礼反目，被压抑的文明外衣在极端情境下轰然崩塌。',
    quote: '有时候，文明只是一层薄薄的外衣。',
    image: 'images/m086.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/17475/sid/1/nid/1.html',
  },
  {
    id: 'm087', rank: 87, title: '英国病人', originalTitle: 'The English Patient', year: 2000,
    director: '安东尼·明格拉', cast: ['拉尔夫·费因斯', '朱丽叶·比诺什', '克里斯汀·斯科特·托马斯', '威廉·达福'],
    categories: ['爱情', '剧情', '战争'], rating: 8.5, region: '英国',
    description: '二战末期，面目全非的神秘病人在意大利修道院中，缓缓揭开一段跨越沙漠与地图的禁忌之恋。注：以2000年加长版计入。',
    quote: '我每周都期望自己死去，但天主却不愿意。',
    image: 'images/m087.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/17250/sid/1/nid/1.html',
  },
  {
    id: 'm088', rank: 88, title: '完美陌生人', originalTitle: 'Perfetti sconosciuti', year: 2016,
    director: '保罗·杰诺维塞', cast: ['马可·贾利尼', '卡西娅·史穆特妮亚克', '阿尔芭·洛瓦赫', '爱德华多·莱奥'],
    categories: ['剧情', '喜剧'], rating: 8.6, region: '意大利',
    description: '七位好友聚会时玩起共享所有手机信息的游戏，每个消息都引爆一个秘密。被翻拍数十个国家的现象级小成本神作。',
    quote: '手机里有我们的一切，它是我们生活的黑匣子。',
    image: 'images/m088.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/173858/sid/1/nid/1.html',
  },
  {
    id: 'm089', rank: 89, title: '禁闭岛', originalTitle: 'Shutter Island', year: 2010,
    director: '马丁·斯科塞斯', cast: ['莱昂纳多·迪卡普里奥', '马克·鲁弗洛', '本·金斯利', '米歇尔·威廉姆斯'],
    categories: ['悬疑', '剧情', '惊悚'], rating: 8.8, region: '美国',
    description: '联邦警探泰迪来到禁闭岛精神病院调查失踪女患者。斯科塞斯用层层迷雾包裹终极反转，让人分不清谁是疯子。',
    quote: '像怪物一样活着，还是像好人一样死去？',
    image: 'images/m089.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/213037/sid/1/nid/1.html',
  },
  {
    id: 'm090', rank: 90, title: '天才枪手', originalTitle: 'Bad Genius', year: 2017,
    director: '纳塔吾·彭皮里亚', cast: ['茱蒂蒙·琼查容苏因', '查侬·散顶腾古', '依莎亚·贺苏汪', '披纳若·苏潘平佑'],
    categories: ['悬疑', '犯罪', '剧情'], rating: 8.5, region: '泰国',
    description: '天才少女琳用钢琴指法帮富家子弟在国际考试中作弊。将考场作弊拍出谍战片的紧张感，泰国年度现象级电影。',
    quote: '就算你再诚实，这个世界还是会欺骗你。',
    image: 'images/m090.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/247800/sid/1/nid/1.html',
  },

  // ====================== Top 91-100 ======================
  {
    id: 'm091', rank: 91, title: '雨果', originalTitle: 'Hugo', year: 2011,
    director: '马丁·斯科塞斯', cast: ['阿萨·巴特菲尔德', '科洛·莫瑞兹', '本·金斯利', '萨莎·拜伦·科恩'],
    categories: ['奇幻', '冒险', '剧情'], rating: 7.8, region: '美国',
    description: '孤儿雨果在巴黎火车站守护一座神秘机器人，意外揭开电影先驱梅里爱的传奇往事。斯科塞斯写给电影最深情的情书。',
    quote: '如果失去了目标，就像机器坏了一样。',
    image: 'images/m091.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/174143/sid/1/nid/1.html',
  },
  {
    id: 'm092', rank: 92, title: '疯狂原始人', originalTitle: 'The Croods', year: 2013,
    director: '柯克·德·米科 / 克里斯·桑德斯', cast: ['尼古拉斯·凯奇', '艾玛·斯通', '瑞安·雷诺兹', '凯瑟琳·基纳'],
    categories: ['动画', '冒险', '喜剧'], rating: 8.7, region: '美国',
    description: '原始人咕噜一家在世界末日般的动荡中寻找新家园。梦工厂用绚丽色彩和密集笑点讲述接受新事物、拥抱明天的主题。',
    quote: '不要害怕，追随光。',
    image: 'images/m092.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/204067/sid/1/nid/1.html',
  },
  {
    id: 'm093', rank: 93, title: '大卫·戈尔的一生', originalTitle: 'The Life of David Gale', year: 2003,
    director: '艾伦·帕克', cast: ['凯文·史派西', '凯特·温斯莱特', '劳拉·琳妮', '加布里埃尔·曼'],
    categories: ['悬疑', '剧情', '犯罪'], rating: 8.7, region: '美国',
    description: '即将被处决的反死刑教授大卫·戈尔向记者讲述最后三天真相。最后一刻的反转让所有人重新思考死刑的意义。',
    quote: '用死来证明生的价值。',
    image: 'images/m093.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/17106/sid/1/nid/1.html',
  },
  {
    id: 'm094', rank: 94, title: '初恋这件小事', originalTitle: 'First Love', year: 2010,
    director: '普特鹏·普罗萨卡·那·萨克那卡林', cast: ['马里奥·毛瑞尔', '平采娜·乐维瑟派布恩', '苏达拉·布查蓬', '雅琳达·邦恩纳克'],
    categories: ['爱情', '喜剧', '剧情'], rating: 8.5, region: '泰国',
    description: '丑小鸭小水为暗恋的帅气学长阿亮努力变美变优秀。每个人都能从中看到自己青春期那场无疾而终又闪闪发光的暗恋。',
    quote: '我一直在等那个人从美国回来。',
    image: 'images/m094.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/213117/sid/1/nid/1.html',
  },
  {
    id: 'm095', rank: 95, title: '一一', originalTitle: 'Yi Yi', year: 2000,
    director: '杨德昌', cast: ['吴念真', '金燕玲', '李凯莉', '张洋洋'],
    categories: ['剧情', '家庭'], rating: 9.1, region: '中国台湾',
    description: '台北中产家庭简南俊三代人各自面对生命困境。杨德昌用三小时拍完了一整个人生的全部面貌——从婚礼到葬礼。',
    quote: '电影发明以后，人类的生命至少延长了三倍。',
    image: 'images/m095.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/246019/sid/1/nid/1.html',
  },
  {
    id: 'm096', rank: 96, title: '异形：契约', originalTitle: 'Alien: Covenant', year: 2017,
    director: '雷德利·斯科特', cast: ['迈克尔·法斯宾德', '凯瑟琳·沃特斯顿', '比利·克鲁德普', '丹尼·麦克布莱德'],
    categories: ['科幻', '恐怖', '惊悚'], rating: 7.4, region: '美国',
    description: '殖民飞船契约号船员抵达未知星球发现大卫幸存。法鲨一人分饰两角，将AI的造物主情结演到了哲学高度。',
    quote: '我在天堂服役，却被放逐到地狱。',
    image: 'images/m096.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/239161/sid/1/nid/1.html',
  },
  {
    id: 'm097', rank: 97, title: '源代码', originalTitle: 'Source Code', year: 2011,
    director: '邓肯·琼斯', cast: ['杰克·吉伦哈尔', '维拉·法米加', '米歇尔·莫娜汉', '杰弗里·怀特'],
    categories: ['科幻', '悬疑', '动作'], rating: 8.5, region: '美国',
    description: '飞行员柯尔特在列车爆炸案8分钟循环中不断穿越寻找炸弹客。吉伦哈尔将科幻概念化为人性深处的终极拷问。',
    quote: '如果你只有一分钟可活，你会怎么做？',
    image: 'images/m097.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/24249/sid/1/nid/1.html',
  },
  {
    id: 'm098', rank: 98, title: '聚焦', originalTitle: 'Spotlight', year: 2015,
    director: '汤姆·麦卡锡', cast: ['马克·鲁弗洛', '迈克尔·基顿', '瑞秋·麦克亚当斯', '列维·施瑞博尔'],
    categories: ['剧情', '传记', '历史'], rating: 8.8, region: '美国',
    description: '波士顿环球报聚焦小组揭露天主教会系统性娈童丑闻。克制冷静的新闻调查实录，真正的好报道比任何虚构都震撼人心。',
    quote: '是体制在保护这些犯罪，而不是个别神父。',
    image: 'images/m098.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/238816/sid/1/nid/1.html',
  },
  {
    id: 'm099', rank: 99, title: '辉夜姬物语', originalTitle: 'The Tale of the Princess Kaguya', year: 2013,
    director: '高畑勋', cast: ['朝仓亚纪', '高良健吾', '地井武男', '宫本信子'],
    categories: ['动画', '奇幻', '剧情'], rating: 8.5, region: '日本',
    description: '竹取翁在竹中发现女婴，辉夜姬从乡村到宫廷追寻自由与真实。高畑勋八年手绘水墨，吉卜力最被低估的伟大杰作。',
    quote: '我来这人间，活过、爱过、痛过，就足够了。',
    image: 'images/m099.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/210456/sid/1/nid/1.html',
  },
  {
    id: 'm100', rank: 100, title: '釜山行', originalTitle: 'Train to Busan', year: 2016,
    director: '延尚昊', cast: ['孔刘', '郑有美', '马东锡', '金秀安'],
    categories: ['动作', '惊悚', '剧情'], rating: 8.6, region: '韩国',
    description: '首尔开往釜山的高铁上僵尸病毒爆发，乘客们在封闭车厢中奋力求生。亚洲丧尸片天花板，马东锡一拳封神，结尾父女情泪目。',
    quote: '爸爸们本来就是为了自己的孩子才变得这么弱。',
    image: 'images/m100.jpg', detailUrl: 'https://xiaoheimi.cc/index.php/vod/play/id/20298/sid/1/nid/1.html',
  },
];